In [1]:
import numpy as np
import pandas as pd

In [27]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_colwidth', None)

In [3]:
df = pd.read_csv('../data/processed/gurgaon_properties_cleaned_1.csv')
df.sample(5)

,society,property_type,sector,price(cr),price_per_sqft,Area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2111,Elevate,flat,sector 50,6.75,19882.0,3395.0,Built Up area: 3395 (315.41 sq.m.),4,4,0,Not available,10.0,NaN,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
927,DLF Ridgewood Estate,flat,sector 28,2.00,14598.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,3,1,Not available,12.0,North-East,10+ Year Old,"['Huda Metro Station', 'Sahara Mall', ""Oyster'...","['4 Fan', '1 Exhaust Fan', '3 Geyser', '8 Ligh...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1703,Tulip Violet,flat,sector 69,1.38,8972.0,1538.0,Carpet area: 1538 (142.88 sq.m.),3,3,1,Not available,12.0,West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Centrally Air Conditioned', 'Water purifier'..."
2924,Umang Monsoon Breeze,flat,sector 78,1.20,6493.0,1848.0,Super Built up area 2250(209.03 sq.m.)Carpet a...,3,3,2,Pooja Room,8.0,NaN,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...","['1 Water Purifier', '1 Fridge', '5 Fan', '1 E...","['Piped-gas', 'Natural Light']"
3021,Vipul Tatvam Villa,house,sector 48,8.50,21250.0,4000.0,Plot area 4000(371.61 sq.m.),4,5,3+,"Pooja Room,Study Room,Servant Room,Others",2.0,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...","['5 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Private Gard..."

In [4]:
df.duplicated().sum()

np.int64(121)

1. areaWithType -> Tranforming this single column into 3 columns (superBuiltUpArea,BuiltUpArea,CarpetArea)

In [5]:
df['areaWithType']

0                          Carpet area: 900 (83.61 sq.m.)
1                          Carpet area: 650 (60.39 sq.m.)
2                          Carpet area: 595 (55.28 sq.m.)
3                        Carpet area: 1200 (111.48 sq.m.)
4                  Super Built up area 1345(124.95 sq.m.)
5                        Built Up area: 654 (60.76 sq.m.)
6                  Super Built up area 1500(139.35 sq.m.)
7                        Carpet area: 2290 (212.75 sq.m.)
8       Built Up area: 1350 (125.42 sq.m.)Carpet area:...
9                      Built Up area: 2813 (261.34 sq.m.)
10                        Carpet area: 1075 (99.87 sq.m.)
11                         Carpet area: 519 (48.22 sq.m.)
12                        Carpet area: 1945 (180.7 sq.m.)
13                 Super Built up area 1385(128.67 sq.m.)
14                 Super Built up area 1300(120.77 sq.m.)
15      Built Up area: 2343 (217.67 sq.m.)Carpet area:...
16                       Built Up area: 639 (59.37 sq.m.)
17                         Carpet area: 915 (85.01 sq.m.)
18                  Super Built up area 2100(195.1 sq.m.)
19                       Carpet area: 1103 (102.47 sq.m.)
20                 Super Built up area 2150(199.74 sq.m.)
21                 Super Built up area 1103(102.47 sq.m.)
22                       Carpet area: 2025 (188.13 sq.m.)
23                 Super Built up area 2217(205.97 sq.m.)
24                         Carpet area: 531 (49.33 sq.m.)
25      Built Up area: 3355 (311.69 sq.m.)Carpet area:...
26                       Carpet area: 2880 (267.56 sq.m.)
27                         Carpet area: 750 (69.68 sq.m.)
28      Built Up area: 1056 (98.11 sq.m.)Carpet area: ...
29                          Carpet area: 66 (55.18 sq.m.)
30      Super Built up area 3200(297.29 sq.m.)Carpet a...
31                      Carpet area: 625.47 (58.11 sq.m.)
32                     Built Up area: 1300 (120.77 sq.m.)
33                       Carpet area: 1300 (120.77 sq.m.)
34                 Super Built up area 1180(109.63 sq.m.)
35      Super Built up area 2030(188.59 sq.m.)Carpet a...
36      Super Built up area 655(60.85 sq.m.)Carpet are...
37      Super Built up area 1365(126.81 sq.m.)Built Up...
38                       Carpet area: 1320 (122.63 sq.m.)
39                       Carpet area: 1210 (112.41 sq.m.)
40                       Carpet area: 2002 (185.99 sq.m.)
41                 Super Built up area 1960(182.09 sq.m.)
42                         Carpet area: 700 (65.03 sq.m.)
43      Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...
44                       Carpet area: 2727 (253.35 sq.m.)
45                       Carpet area: 1385 (128.67 sq.m.)
46                       Carpet area: 1829 (169.92 sq.m.)
47                        Carpet area: 2100 (195.1 sq.m.)
48                       Carpet area: 1650 (153.29 sq.m.)
49                       Carpet area: 1100 (102.19 sq.m.)
50                       Carpet area: 1530 (142.14 sq.m.)
51                       Carpet area: 1120 (104.05 sq.m.)
52                       Carpet area: 1250 (116.13 sq.m.)
53                       Carpet area: 2651 (246.29 sq.m.)
54                         Carpet area: 450 (41.81 sq.m.)
55                 Super Built up area 1570(145.86 sq.m.)
56                  Super Built up area 1198(111.3 sq.m.)
57      Super Built up area 1450(134.71 sq.m.)Carpet a...
58                 Super Built up area 1897(176.24 sq.m.)
59      Super Built up area 1260(117.06 sq.m.)Carpet a...
60                 Super Built up area 1725(160.26 sq.m.)
61                 Super Built up area 2200(204.39 sq.m.)
62                 Super Built up area 1875(174.19 sq.m.)
63                 Super Built up area 2250(209.03 sq.m.)
64               Super Built up area 1056.58(98.16 sq.m.)
65                   Super Built up area 560(52.03 sq.m.)
66      Built Up area: 990 (91.97 sq.m.)Carpet area: 9...
67                 Super Built up area 1370(127.28 sq.m.)
68                      Carpet area: 531.57 (49.38 sq.m.)
69      Super Built up area 575(53.42 sq.m.)Carpet are...
70                        Carpet area: 1452 (134.9 sq.m.)
71                        Carpet area: 1423 (132.2 sq.m.)
72                         Carpet area: 640 (59.46 sq.m.)
73                         Carpet area: 822 (76.37 sq.m.)
74                 Super Built up area 2159(200.58 sq.m.)
75                 Super Built up area 1950(181.16 sq.m.)
76      Built Up area: 1300 (120.77 sq.m.)Carpet area:...
77      Built Up area: 1423 (132.2 sq.m.)Carpet area: ...
78                     Carpet area: 58141 (5401.48 sq.m.)
79                 Super Built up area 3670(340.95 sq.m.)
80      Built Up area: 743 (69.03 sq.m.)Carpet area: 6...
81      Super Built up area 2250(209.03 sq.m.)Carpet a...
82                       Carpet area: 2177 (202.25 sq.m.)
83                         Carpet area: 650 (60.39 sq.m.)
84                         Carpet area: 900 (83.61 sq.m.)
85                       Carpet area: 1118 (103.87 sq.m.)
86      Built Up area: 1433 (133.13 sq.m.)Carpet area:...
87                 Super Built up area 1120(104.05 sq.m.)
88                     Built Up area: 1120 (104.05 sq.m.)
89                     Built Up area: 1996 (185.43 sq.m.)
90                       Carpet area: 1080 (100.34 sq.m.)
91                 Super Built up area 2727(253.35 sq.m.)
92                  Super Built up area 1789(166.2 sq.m.)
93                       Carpet area: 1380 (128.21 sq.m.)
94                     Built Up area: 1540 (143.07 sq.m.)
95      Super Built up area 1629(151.34 sq.m.)Carpet a...
96                 Super Built up area 1828(169.83 sq.m.)
97                       Carpet area: 1950 (181.16 sq.m.)
98                       Carpet area: 1200 (111.48 sq.m.)
99                          Carpet area: 324 (30.1 sq.m.)
100     Super Built up area 2000(185.81 sq.m.)Built Up...
101                      Carpet area: 1929 (179.21 sq.m.)
102                                Super Built up area 89
103     Super Built up area 700(65.03 sq.m.)Carpet are...
104     Built Up area: 965 (89.65 sq.m.)Carpet area: 6...
105     Super Built up area 524(48.68 sq.m.)Carpet are...
106                     Carpet area: 581.41 (54.01 sq.m.)
107     Super Built up area 1197.8(111.28 sq.m.)Carpet...
108                 Super Built up area 1310(121.7 sq.m.)
109                  Carpet area: 569243 (52884.41 sq.m.)
110                        Carpet area: 750 (69.68 sq.m.)
111                      Carpet area: 1557 (144.65 sq.m.)
112                Super Built up area 1440(133.78 sq.m.)
113                      Carpet area: 2597 (241.27 sq.m.)
114     Super Built up area 1940(180.23 sq.m.)Carpet a...
115                        Carpet area: 567 (52.68 sq.m.)
116     Super Built up area 623(57.88 sq.m.)Carpet are...
117                        Carpet area: 629 (58.44 sq.m.)
118                 Super Built up area 1423(132.2 sq.m.)
119     Super Built up area 1450(134.71 sq.m.)Carpet a...
120                Super Built up area 1400(130.06 sq.m.)
121                Super Built up area 2000(185.81 sq.m.)
122                      Carpet area: 1276 (118.54 sq.m.)
123                Super Built up area 1276(118.54 sq.m.)
124                    Built Up area: 1259 (116.96 sq.m.)
125                Super Built up area 1640(152.36 sq.m.)
126                      Built Up area: 610 (56.67 sq.m.)
127                Super Built up area 1690(157.01 sq.m.)
128                     Carpet area: 481.74 (44.76 sq.m.)
129                        Carpet area: 531 (49.33 sq.m.)
130                 Super Built up area 215(179.77 sq.m.)
131     Super Built up area 1950(181.16 sq.m.)Built Up...
132                        Carpet area: 591 (54.91 sq.m.)
133                  Super Built up area 546(50.73 sq.m.)
134     Super Built up area 1530(142.14 sq.m.)Built Up...
135                      Carpet area: 1910 (177.44 sq.m.)
136                 Super Built up area 1789(166.2 sq.m.)
137                    Built Up area: 2040 (189.52 sq.m.)
138     Super Built up area 4350(404.13 sq.m.)Carpet a...
139     Super Built up area 2500(232.26 sq.m.)Built Up...
140                           Carpet area: 958 (89 sq.m.)
141                      Carpet area: 1225 (113.81 sq.m.)
142     Super Built up area 1751(162.67 sq.m.)Carpet a...
143                Super Built up area 1689(156.91 sq.m.)
144                        Carpet area: 700 (65.03 sq.m.)
145                Super Built up area 1828(169.83 sq.m.)
146     Built Up area: 1440 (133.78 sq.m.)Carpet area:...
147     Built Up area: 1468 (136.38 sq.m.)Carpet area:...
148     Super Built up area 2191(203.55 sq.m.)Built Up...
149                        Carpet area: 626 (58.16 sq.m.)
150     Built Up area: 1570 (145.86 sq.m.)Carpet area:...
151                        Carpet area: 520 (48.31 sq.m.)
152                Super Built up area 1828(169.83 sq.m.)
153              Built Up area: 118 Carpet area: 86 sq.m.
154                      Carpet area: 1630 (151.43 sq.m.)
155     Super Built up area 1275(118.45 sq.m.)Carpet a...
156                        Carpet area: 514 (47.75 sq.m.)
157     Super Built up area 1735(161.19 sq.m.)Carpet a...
158                      Carpet area: 2300 (213.68 sq.m.)
159                   Super Built up area 380(35.3 sq.m.)
160                      Carpet area: 1105 (102.66 sq.m.)
161                Super Built up area 1365(126.81 sq.m.)
162                Super Built up area 1252(116.31 sq.m.)
163     Built Up area: 1000 (92.9 sq.m.)Carpet area: 6...
164                      Carpet area: 4500 (418.06 sq.m.)
165                Super Built up area 1850(171.87 sq.m.)
166                Super Built up area 2364(219.62 sq.m.)
167                Super Built up area 2727(253.35 sq.m.)
168                      Carpet area: 1180 (109.63 sq.m.)
169                Super Built up area 1865(173.26 sq.m.)
170                      Carpet area: 1537 (142.79 sq.m.)
171                    Built Up area: 1758 (163.32 sq.m.)
172                Super Built up area 2408(223.71 sq.m.)
173                      Built Up area: 826 (76.74 sq.m.)
174                Super Built up area 1262(117.24 sq.m.)
175                      Carpet area: 2215 (205.78 sq.m.)
176                                    Carpet area: 127.3
177     Built Up area: 1430 (132.85 sq.m.)Carpet area:...
178                      Built Up area: 700 (65.03 sq.m.)
179                      Built Up area: 587 (54.53 sq.m.)
180     Super Built up area 1534(142.51 sq.m.)Built Up...
181                        Carpet area: 946 (87.89 sq.m.)
182                      Carpet area: 2298 (213.49 sq.m.)
183                Super Built up area 1320(122.63 sq.m.)
184                      Carpet area: 2400 (222.97 sq.m.)
185                      Carpet area: 1262 (117.24 sq.m.)
186                    Built Up area: 1433 (133.13 sq.m.)
187     Built Up area: 743 (69.03 sq.m.)Carpet area: 5...
188     Built Up area: 750 (69.68 sq.m.)Carpet area: 6...
189     Built Up area: 950 (88.26 sq.m.)Carpet area: 7...
190                    Built Up area: 2400 (222.97 sq.m.)
191                Super Built up area 1999(185.71 sq.m.)
192                      Carpet area: 2302 (213.86 sq.m.)
193                        Carpet area: 710 (65.96 sq.m.)
194     Super Built up area 1000(92.9 sq.m.)Carpet are...
195                       Carpet area: 1069 (99.31 sq.m.)
196                Super Built up area 1433(133.13 sq.m.)
197     Built Up area: 546 (50.73 sq.m.)Carpet area: 4...
198                  Super Built up area 600(55.74 sq.m.)
199                        Carpet area: 780 (72.46 sq.m.)
200             Super Built up area 1252.13(116.33 sq.m.)
201                        Carpet area: 850 (78.97 sq.m.)
202     Super Built up area 1285(119.38 sq.m.)Built Up...
203                      Carpet area: 1400 (130.06 sq.m.)
204     Super Built up area 1452(134.9 sq.m.)Carpet ar...
205                Super Built up area 1828(169.83 sq.m.)
206                Super Built up area 2040(189.52 sq.m.)
207                      Carpet area: 5140 (477.52 sq.m.)
208                Super Built up area 1828(169.83 sq.m.)
209                Super Built up area 1261(117.15 sq.m.)
210                Super Built up area 1828(169.83 sq.m.)
211                    Built Up area: 2900 (269.42 sq.m.)
212                        Carpet area: 990 (91.97 sq.m.)
213               Super Built up area 568.46(52.81 sq.m.)
214                Super Built up area 1364(126.72 sq.m.)
215                 Super Built up area 1620(150.5 sq.m.)
216     Super Built up area 1310(121.7 sq.m.)Built Up ...
217                Super Built up area 1295(120.31 sq.m.)
218                        Carpet area: 680 (63.17 sq.m.)
219                Super Built up area 1579(146.69 sq.m.)
220                  Super Built up area 903(83.89 sq.m.)
221                    Built Up area: 1150 (106.84 sq.m.)
222                       Carpet area: 1945 (180.7 sq.m.)
223                      Carpet area: 1600 (148.64 sq.m.)
224     Super Built up area 1110(103.12 sq.m.)Built Up...
225                      Carpet area: 2025 (188.13 sq.m.)
226                      Carpet area: 1200 (111.48 sq.m.)
227                Super Built up area 1660(154.22 sq.m.)
228     Super Built up area 583(54.16 sq.m.)Built Up a...
229                    Built Up area: 1622 (150.69 sq.m.)
230                        Carpet area: 900 (83.61 sq.m.)
231     Super Built up area 1081(100.43 sq.m.)Carpet a...
232                Super Built up area 1485(137.96 sq.m.)
233                      Carpet area: 2050 (190.45 sq.m.)
234                       Carpet area: 1775 (164.9 sq.m.)
235     Super Built up area 850(78.97 sq.m.)Built Up a...
236                      Carpet area: 1433 (133.13 sq.m.)
237     Super Built up area 915(85.01 sq.m.)Carpet are...
238                Super Built up area 2940(273.13 sq.m.)
239                        Carpet area: 675 (62.71 sq.m.)
240                      Carpet area: 1151 (106.93 sq.m.)
241                Super Built up area 1260(117.06 sq.m.)
242                        Carpet area: 800 (74.32 sq.m.)
243                      Carpet area: 1600 (148.64 sq.m.)
244     Super Built up area 2350(218.32 sq.m.)Built Up...
245                      Carpet area: 1340 (124.49 sq.m.)
246                      Carpet area: 1350 (125.42 sq.m.)
247                Super Built up area 2905(269.88 sq.m.)
248                        Carpet area: 716 (66.52 sq.m.)
249                      Carpet area: 2800 (260.13 sq.m.)
250                      Carpet area: 1575 (146.32 sq.m.)
251     Super Built up area 1549(143.91 sq.m.)Carpet a...
252                Super Built up area 2467(229.19 sq.m.)
253                Super Built up area 1351(125.51 sq.m.)
254                Super Built up area 1365(126.81 sq.m.)
255                     Built Up area: 140 (117.06 sq.m.)
256                Super Built up area 1565(145.39 sq.m.)
257     Super Built up area 1295(120.31 sq.m.)Carpet a...
258                Super Built up area 1361(126.44 sq.m.)
259                      Carpet area: 1326 (123.19 sq.m.)
260                Super Built up area 1960(182.09 sq.m.)
261                        Carpet area: 997 (92.62 sq.m.)
262                     Built Up area: 1310 (121.7 sq.m.)
263                     Built Up area: 1310 (121.7 sq.m.)
264                Super Built up area 1095(101.73 sq.m.)
265     Super Built up area 1380(128.21 sq.m.)Built Up...
266                     Built Up area: 1423 (132.2 sq.m.)
267                      Built Up area: 700 (65.03 sq.m.)
268                    Built Up area: 1997 (185.53 sq.m.)
269                    Built Up area: 1523 (141.49 sq.m.)
270                    Built Up area: 1382 (128.39 sq.m.)
271     Built Up area: 804 (74.69 sq.m.)Carpet area: 6...
272                    Built Up area: 3350 (311.23 sq.m.)
273     Super Built up area 2408(223.71 sq.m.)Built Up...
274                Super Built up area 2600(241.55 sq.m.)
275     Built Up area: 2200 (204.39 sq.m.)Carpet area:...
276                      Carpet area: 3844 (357.12 sq.m.)
277                Super Built up area 1780(165.37 sq.m.)
278     Super Built up area 2000(185.81 sq.m.)Carpet a...
279                      Carpet area: 4328 (402.08 sq.m.)
280                       Carpet area: 2452 (227.8 sq.m.)
281                       Carpet area: 1508 (140.1 sq.m.)
282     Super Built up area 1500(139.35 sq.m.)Carpet a...
283                Super Built up area 1407(130.71 sq.m.)
284                Super Built up area 1630(151.43 sq.m.)
285                        Carpet area: 745 (69.21 sq.m.)
286                      Carpet area: 1806 (167.78 sq.m.)
287               Built Up area: 97 Carpet area: 92 sq.m.
288                      Carpet area: 1450 (134.71 sq.m.)
289                Super Built up area 1100(102.19 sq.m.)
290                      Carpet area: 2300 (213.68 sq.m.)
291                Super Built up area 2786(258.83 sq.m.)
292     Built Up area: 1852 (172.06 sq.m.)Carpet area:...
293                    Carpet area: 1249.65 (116.1 sq.m.)
294                Super Built up area 2605(242.01 sq.m.)
295                      Carpet area: 1549 (143.91 sq.m.)
296     Super Built up area 1650(153.29 sq.m.)Carpet a...
297                      Carpet area: 1671 (155.24 sq.m.)
298                Super Built up area 1350(125.42 sq.m.)
299     Built Up area: 2060 (191.38 sq.m.)Carpet area:...
300                      Carpet area: 2000 (185.81 sq.m.)
301                       Carpet area: 2100 (195.1 sq.m.)
302                      Carpet area: 2750 (255.48 sq.m.)
303                Super Built up area 1572(146.04 sq.m.)
304     Super Built up area 1870(173.73 sq.m.)Built Up...
305     Built Up area: 2200 (204.39 sq.m.)Carpet area:...
306                      Carpet area: 3844 (357.12 sq.m.)
307                Super Built up area 1780(165.37 sq.m.)
308     Super Built up area 2000(185.81 sq.m.)Carpet a...
309                       Carpet area: 2452 (227.8 sq.m.)
310                       Carpet area: 1508 (140.1 sq.m.)
311                Super Built up area 1407(130.71 sq.m.)
312                        Carpet area: 745 (69.21 sq.m.)
313                      Carpet area: 1806 (167.78 sq.m.)
314               Built Up area: 97 Carpet area: 92 sq.m.
315                      Carpet area: 1450 (134.71 sq.m.)
316                Super Built up area 1100(102.19 sq.m.)
317                      Carpet area: 2300 (213.68 sq.m.)
318                Super Built up area 2786(258.83 sq.m.)
319     Built Up area: 1852 (172.06 sq.m.)Carpet area:...
320                Super Built up area 2605(242.01 sq.m.)
321     Super Built up area 1650(153.29 sq.m.)Carpet a...
322                Super Built up area 1350(125.42 sq.m.)
323                      Carpet area: 2000 (185.81 sq.m.)
324                       Carpet area: 2100 (195.1 sq.m.)
325                Super Built up area 1572(146.04 sq.m.)
326                Super Built up area 2892(268.68 sq.m.)
327                Super Built up area 2143(199.09 sq.m.)
328                      Carpet area: 1304 (121.15 sq.m.)
329     Super Built up area 1758(163.32 sq.m.)Carpet a...
330     Built Up area: 1250 (116.13 sq.m.)Carpet area:...
331                Super Built up area 4553(422.99 sq.m.)
332                Super Built up area 1900(176.52 sq.m.)
333                Super Built up area 1743(161.93 sq.m.)
334                     Carpet area: 457.81 (42.53 sq.m.)
335                Super Built up area 3025(281.03 sq.m.)
336                Super Built up area 1990(184.88 sq.m.)
337                Super Built up area 1385(128.67 sq.m.)
338                      Built Up area: 826 (76.74 sq.m.)
339     Super Built up area 1283(119.19 sq.m.)Built Up...
340     Super Built up area 2344(217.76 sq.m.)Built Up...
341                Super Built up area 1383(128.48 sq.m.)
342                      Carpet area: 1150 (106.84 sq.m.)
343     Super Built up area 2200(204.39 sq.m.)Built Up...

In [6]:
df['areaWithType'].isnull().sum()

np.int64(0)

In [7]:
df['areaWithType'].value_counts()

areaWithType
Plot area 360(301.01 sq.m.)                                                                                                     36
Plot area 300(250.84 sq.m.)                                                                                                     26
Plot area 200(167.23 sq.m.)                                                                                                     19
Plot area 502(419.74 sq.m.)                                                                                                     18
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Plot area 270(225.75 sq.m.)                                                                                                     16
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Plot area 150(125.42 sq.m.)                                                                                                     14
Plot area 500(418.06 sq.m.)                                                                                                     13
Plot area 900(83.61 sq.m.)                                                                                                      13
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Carpet area: 900 (83.61 sq.m.)                                                                                                  11
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Carpet area: 1450 (134.71 sq.m.)                                                                                                11
Plot area 215(179.77 sq.m.)                                                                                                     11
Plot area 400(334.45 sq.m.)                                                                                                     11
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Plot area 316(264.22 sq.m.)                                                                                                      9
Plot area 161(134.62 sq.m.)                                                                                                      9
Plot area 250(209.03 sq.m.)                                                                                                      9
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Carpet area: 1300 (120.77 sq.m.)                                                                                                 8
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Carpet area: 1350 (125.42 sq.m.)                                                                                                 8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Plot area 240(200.67 sq.m.)                                                                                                      8
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Plot area 100(83.61 sq.m.)                                                                                                       7
Plot area 263(219.9 sq.m.)                                                                                                       7
Plot area 173(144.65 sq.m.)                                                                                                      7
Plot area 600(501.68 sq.m.)                                                                                                      7
Super Built up area 2100(195.1 sq.m.)                                                                                            6
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Carpet area: 2300 (213.68 sq.m.)                                                                                                 6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Super Built up area 1200(111.48 sq.m.)                                                                                           6
Built Up area: 1350 (125.42 sq.m.)                                                                                               6
Plot area 160(133.78 sq.m.)                                                                                                      6
Plot area 60(50.17 sq.m.)                                                                                                        6
Plot area 204(170.57 sq.m.)                                                                                                      6
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Super Built up area 1750(162.58 sq.m.)                                                                                           5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Plot area 290(242.48 sq.m.)                                                                                                      5
Plot area 192(160.54 sq.m.)                                                                                                      5
Plot area 450(41.81 sq.m.)                                                                                                       5
Plot area 1000(836.13 sq.m.)                                                                                                     5
Plot area 692(578.6 sq.m.)                                                                                                       5
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Built Up area: 1423 (132.2 sq.m.)                                                                                                4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Built Up area: 2250 (209.03 sq.m.)                                                                                               4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Built Up area: 1100 (102.19 sq.m.)                                                                                               4
Built Up area: 1000 (92.9 sq.m.)                                                                                                 4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Built Up area: 2000 (185.81 sq.m.)                                                                                               4
Carpet area: 500 (46.45 sq.m.)                                                                                                   4
Plot area 62(51.84 sq.m.)                                                                                                        4
Plot area 4000(371.61 sq.m.)                                                                                                     4

In [8]:
df.insert(loc=7,column='superBuiltUpArea',value=np.nan)
df.insert(loc=8,column='builtUpArea',value=np.nan)
df.insert(loc=9,column='carpetArea',value=np.nan)
df.sample(5)

,society,property_type,sector,price(cr),price_per_sqft,Area,areaWithType,superBuiltUpArea,builtUpArea,carpetArea,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
914,MM Woodshire,flat,sector 107,0.98,6421.0,1526.0,Super Built up area 1534(142.51 sq.m.)Carpet a...,NaN,NaN,NaN,2,2,3,Study Room,7.0,West,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...","['4 Fan', '1 Exhaust Fan', '4 Light', '1 Curta...","['Centrally Air Conditioned', 'Water purifier'..."
1763,Antriksh Heights,flat,sector 84,0.90,6206.0,1450.0,Super Built up area 1725(160.26 sq.m.)Built Up...,NaN,NaN,NaN,3,3,3+,Not available,12.0,North-East,1 to 5 Year Old,"['Old Bengali Market', 'MatriKiran High School...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
867,Vatika City,flat,sector 49,1.98,9074.0,2182.0,Super Built up area 2182(202.71 sq.m.)Built Up...,NaN,NaN,NaN,3,4,3,Servant Room,9.0,South-East,5 to 10 Year Old,"['BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
370,Ambience Lagoon,flat,sector 24,4.25,13281.0,3200.0,Super Built up area 3200(297.29 sq.m.)Carpet a...,NaN,NaN,NaN,3,4,3+,"Servant Room,Store Room",3.0,East,10+ Year Old,"['Micromax moulsari avenue metro station', 'In...","['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Li..."
541,MM Merlin,flat,sector 67,2.80,13678.0,2047.0,Super Built up area 2047(190.17 sq.m.)Carpet a...,NaN,NaN,NaN,3,3,3,Servant Room,5.0,North-East,5 to 10 Year Old,"['Airia Mall', 'Golf Course Extension Road', '...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."

In [9]:
import re
import pandas as pd

def extract_all_areas(text):
    if pd.isna(text):
        return {}
    
    pattern = r"(Super Built up area|Built Up area|Carpet area|Plot area)\s*[:]*\s*(\d+\.?\d*)"
    
    matches = re.findall(pattern, text, flags=re.IGNORECASE)
    
    area_dict = {}
    
    for key, value in matches:
        value = float(value)
        
        # handle sqm conversion ONLY if needed
        # if bracket exists → value already sqft → skip conversion
        if '(' not in text and 'sq.m' in text:
            value = value * 10.764
        
        area_dict[key.lower()] = value
    
    return area_dict

In [10]:
def get_area(text, target):
    areas = extract_all_areas(text)
    return areas.get(target.lower(), None)


df['superBuiltUpArea'] = df['areaWithType'].apply(
    lambda x: get_area(x, 'Super Built up area')
)

df['builtUpArea'] = df['areaWithType'].apply(
    lambda x: get_area(x, 'Built Up area')
)

df['carpetArea'] = df['areaWithType'].apply(
    lambda x: get_area(x, 'Carpet area')
)

# For houses
mask = df['property_type'] == 'house'

df.loc[mask, 'carpetArea'] = df.loc[mask, 'areaWithType'].apply(
    lambda x: get_area(x, 'Plot area')
)

In [11]:
df.sample(5)

,society,property_type,sector,price(cr),price_per_sqft,Area,areaWithType,superBuiltUpArea,builtUpArea,carpetArea,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3024,International City by SOBHA Phase,house,sector 109,6.80,12593.0,5400.0,Plot area 600(501.68 sq.m.),NaN,NaN,600.0,4,5,3,Servant Room,2.0,North-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
1827,Shree Vardhman Flora,flat,sector 90,1.25,4854.0,2575.0,Carpet area: 2575 (239.23 sq.m.),NaN,NaN,2575.0,4,4,3,"Pooja Room,Study Room",10.0,East,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
703,Signature Global Solera,flat,sector 107,0.50,7751.0,645.0,Carpet area: 645 (59.92 sq.m.),NaN,NaN,645.0,3,2,2,Others,6.0,South-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",NaN,"['Intercom Facility', 'Lift(s)', 'Park']"
1525,Tata Primanti,flat,sector 72,4.00,16032.0,2495.0,Super Built up area 2905(269.88 sq.m.)Carpet a...,2905.0,NaN,2495.0,4,5,3+,Servant Room,22.0,West,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","['1 Water Purifier', '1 Exhaust Fan', '6 Geyse...","['Centrally Air Conditioned', 'Water purifier'..."
920,MM Woodshire,flat,sector 107,1.39,5887.0,2361.0,Super Built up area 2361(219.34 sq.m.)Carpet a...,2361.0,NaN,1780.0,3,4,3+,"Servant Room,Pooja Room",6.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...","['7 Fan', '1 Exhaust Fan', '7 Light', '1 Curta...","['Centrally Air Conditioned', 'Water purifier'..."

2. additionalRooms

In [12]:
df['additionalRoom'].isnull().sum()

np.int64(320)

In [13]:
df['additionalRoom'].value_counts()

additionalRoom
Not available                                    1258
Servant Room                                      704
Study Room                                        249
Others                                            225
Pooja Room                                        165
Store Room                                         99
Study Room,Servant Room                            98
Pooja Room,Servant Room                            82
Pooja Room,Study Room,Servant Room,Store Room      71
Servant Room,Others                                60
Pooja Room,Study Room,Servant Room                 54
Pooja Room,Study Room,Servant Room,Others          51
Servant Room,Pooja Room                            38
Servant Room,Store Room                            31
Study Room,Others                                  29
Pooja Room,Study Room                              22
Pooja Room,Others                                  17
Pooja Room,Store Room                              15
Servant Room,Study Room                            12
Study Room,Servant Room,Store Room                 11
Pooja Room,Store Room,Study Room,Servant Room      11
Pooja Room,Servant Room,Others                     11
Study Room,Pooja Room                              10
Servant Room,Study Room,Pooja Room,Store Room      10
Store Room,Servant Room                             8
Study Room,Servant Room,Pooja Room,Store Room       8
Study Room,Servant Room,Others                      7
Pooja Room,Study Room,Store Room                    7
Study Room,Pooja Room,Servant Room                  7
Pooja Room,Servant Room,Store Room                  7
Others,Servant Room                                 6
Servant Room,Pooja Room,Store Room                  6
Pooja Room,Servant Room,Study Room,Store Room       5
Study Room,Servant Room,Store Room,Pooja Room       5
Store Room,Pooja Room                               5
Study Room,Servant Room,Pooja Room                  4
Study Room,Pooja Room,Store Room                    4
Pooja Room,Study Room,Others                        4
Servant Room,Store Room,Pooja Room                  4
Servant Room,Others,Pooja Room                      3
Pooja Room,Study Room,Store Room,Servant Room       3
Servant Room,Pooja Room,Study Room,Store Room       3
Servant Room,Study Room,Pooja Room                  3
Study Room,Pooja Room,Servant Room,Store Room       3
Store Room,Pooja Room,Servant Room                  2
Servant Room,Study Room,Store Room                  2
Study Room,Store Room                               2
Servant Room,Others,Store Room,Pooja Room           2
Store Room,Pooja Room,Study Room                    2
Store Room,Pooja Room,Study Room,Servant Room       2
Study Room,Pooja Room,Store Room,Servant Room       2
Store Room,Study Room                               1
Servant Room,Pooja Room,Store Room,Study Room       1
Servant Room,Pooja Room,Study Room                  1
Others,Study Room                                   1
Servant Room,Study Room,Others                      1
Servant Room,Study Room,Store Room,Pooja Room       1
Study Room,Store Room,Pooja Room                    1
Store Room,Pooja Room,Servant Room,Study Room       1
Servant Room,Store Room,Study Room,Pooja Room       1
Store Room,Servant Room,Study Room,Pooja Room       1
Pooja Room,Store Room,Servant Room                  1
Store Room,Study Room,Servant Room                  1
Store Room,Servant Room,Pooja Room                  1
Study Room,Others,Servant Room                      1
Name: count, dtype: int64

In [14]:
def check_rooms(text,room):
    if pd.isna(text):
        return 0
    
    return 1 if room in text.lower() else 0

In [15]:
df.insert(loc=14,column='poojaRoom',value=df['additionalRoom'].apply(
    lambda x: check_rooms(x,'pooja')
))
df.insert(loc=15,column='studyRoom',value=df['additionalRoom'].apply(
    lambda x: check_rooms(x,'study')
))
df.insert(loc=16,column='storeRoom',value=df['additionalRoom'].apply(
    lambda x: check_rooms(x,'store')
))
df.insert(loc=17,column='servantRoom',value=df['additionalRoom'].apply(
    lambda x: check_rooms(x,'servant')
))
df.insert(loc=18,column='others',value=df['additionalRoom'].apply(
    lambda x: check_rooms(x,'others')
))

In [16]:
df.sample(5)

,society,property_type,sector,price(cr),price_per_sqft,Area,areaWithType,superBuiltUpArea,builtUpArea,carpetArea,bedRoom,bathroom,balcony,additionalRoom,poojaRoom,studyRoom,storeRoom,servantRoom,others,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
668,Orris Aster Court Premier,flat,sector 85,1.49,5820.0,2560.0,Super Built up area 2560(237.83 sq.m.)Built Up...,2560.0,2017.0,1890.0,4,5,3+,Servant Room,0,0,0,1,0,10.0,East,1 to 5 Year Old,"['Propose Metro Station', 'SS Omnia Mall', 'Na...","['1 Stove', '5 AC', '1 Chimney', '1 Modular Ki...","['Lift(s)', 'Maintenance Staff', 'Water Storag..."
3306,Independent,house,sector 7,3.00,11494.0,2610.0,Built Up area: 2610 (242.48 sq.m.),NaN,2610.0,NaN,7,7,0,NaN,0,0,0,0,0,3.0,NaN,undefined,NaN,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
2423,Sare Crescent Parc,flat,sector 92,0.49,4909.0,998.0,Carpet area: 998 (92.72 sq.m.),NaN,NaN,998.0,2,2,2,Not available,0,0,0,0,0,2.0,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2901,Signature Global Synera,flat,sector 81,0.50,7886.0,634.0,Carpet area: 634 (58.9 sq.m.),NaN,NaN,634.0,2,2,1,Not available,0,0,0,0,0,11.0,East,0 to 1 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...","['1 Water Purifier', '3 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
3541,Independent,house,sector 45,10.00,30864.0,3240.0,Plot area 360(301.01 sq.m.),NaN,NaN,360.0,6,6,3+,"Pooja Room,Study Room,Servant Room,Store Room",1,1,1,1,0,4.0,North-East,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...","['4 Bed', '5 Wardrobe', '1 Water Purifier', '7...","['Feng Shui / Vaastu Compliant', 'Centrally Ai..."

3. Age Possession

In [17]:
df['agePossession'].value_counts()

agePossession
1 to 5 Year Old       1669
5 to 10 Year Old       569
0 to 1 Year Old        527
undefined              331
10+ Year Old           308
Under Construction      89
Within 6 months         70
Within 3 months         26
Dec 2023                22
By 2023                 19
By 2024                 17
Dec 2024                16
Mar 2024                14
Jan 2024                 8
Oct 2024                 8
Jun 2024                 7
Dec 2025                 7
Aug 2023                 7
Nov 2023                 5
Oct 2023                 4
By 2025                  4
Sep 2023                 4
Aug 2024                 4
Jul 2024                 4
Feb 2024                 3
Jan 2025                 3
May 2024                 3
Nov 2024                 3
Sep 2025                 2
Dec 2026                 2
Apr 2026                 2
Jul 2027                 2
By 2027                  2
Jan 2026                 2
Jun 2027                 2
Mar 2025                 2
Jul 2025                 2
Aug 2025                 2
Oct 2025                 2
Jan 2027                 1
Jul 2026                 1
Apr 2024                 1
Nov 2025                 1
Sep 2027                 1
Jun 2025                 1
Jan 2028                 1
Aug 2026                 1
Mar 2026                 1
Name: count, dtype: int64

In [18]:
def categorize_age_possession(value):
    if pd.isna(value):
        return "Undefined"
    if "0 to 1 Year Old" in value or "Within 6 months" in value or "Within 3 months" in value:
        return "New Property"
    if "1 to 5 Year Old" in value:
        return "Relatively New"
    if "5 to 10 Year Old" in value:
        return "Moderately Old"
    if "10+ Year Old" in value:
        return "Old Property"
    if "Under Construction" in value or "By" in value:
        return "Under Construction"
    try:
        # For entries like 'May 2024'
        int(value.split(" ")[-1])
        return "Under Construction"
    except:
        return "Undefined"

In [19]:
df['agePossession'] = df['agePossession'].apply(categorize_age_possession)

In [20]:
df['agePossession'].value_counts()

agePossession
Relatively New        1669
New Property           623
Moderately Old         569
Undefined              332
Old Property           308
Under Construction     282
Name: count, dtype: int64

In [21]:
df.sample(5)

,society,property_type,sector,price(cr),price_per_sqft,Area,areaWithType,superBuiltUpArea,builtUpArea,carpetArea,bedRoom,bathroom,balcony,additionalRoom,poojaRoom,studyRoom,storeRoom,servantRoom,others,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2227,GLS Arawali Homes,flat,sohna road,0.26,4513.0,576.0,Carpet area: 576 (53.51 sq.m.),NaN,NaN,576.0,2,2,2,Not available,0,0,0,0,0,4.0,NaN,Relatively New,"['Huda City Centre', 'Golf Course Road', 'Delh...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
3066,Independent,house,sector 17a,3.93,24214.0,1623.0,Plot area 1623(150.78 sq.m.)Built Up area: 162...,NaN,1622.0,1623.0,19,17,3,"Study Room,Servant Room,Store Room,Pooja Room",1,1,1,1,0,4.0,North-West,Relatively New,"['Iffco chowk metro station', 'Citi bank ATM',...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
3428,DLF City Plots,house,sector 26,17.30,38734.0,4466.0,Plot area 502(419.74 sq.m.),NaN,NaN,502.0,6,7,3+,"Pooja Room,Store Room,Study Room,Servant Room",1,1,1,1,0,3.0,North,New Property,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...","['1 Exhaust Fan', '6 Geyser', '8 AC', '1 Modul...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
789,Pareena Coban Residences,flat,sector 99a,1.08,6625.0,1630.0,Super Built up area 1997(185.53 sq.m.)Built Up...,1997.0,1750.0,1630.0,3,5,3,"Servant Room,Others",0,0,0,1,1,2.0,West,Relatively New,"['Gopal Super Market', 'Little Need Super Mark...","['5 AC', '1 Modular Kitchen', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Security / F..."
2282,Sidhartha NCR Greens,flat,sector 95,0.56,5656.0,990.0,Super Built up area 990(91.97 sq.m.),990.0,NaN,NaN,2,2,3,Not available,0,0,0,0,0,13.0,NaN,New Property,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",[],"['Power Back-up', 'Lift(s)', 'Park', 'Piped-gas']"

In [28]:
df['furnishDetails']

0          ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
1               ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Geyser', '3 Light', '1 Curtains', '1 Chimney', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
2                                                                                                                                                                                                                                                                         NaN
3                                                                                                                                                                                                                                                                         NaN
4                                                                                                                                                                                                                                                                          []
5                                                                                                                                                                                                                                                                         NaN
6                                                                                                                                                                                                                                                                          []
7                                                                                                                                                                                                                                                                          []
8                                                                                                                                                                                                                                                                         NaN
9                                                                                                                                                                                                                                                                         NaN
10                                                                                                                                                                                                                                                                        NaN
11                                                                                                                                                                                                                                                                        NaN
12           ['1 Water Purifier', '2 Fan', '1 Geyser', '3 Light', '2 AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine']
13                                                                                                                                                                                                                                                                        NaN
14                                                                                                                                                                                                                                                                        NaN
15       ['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
16                                                                                                                                                                                                                                                                        NaN
17                                                                                                                                                                                                                                                                         []
18             ['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Geyser', '1 Light', '1 Modular Kitchen', '1 Chimney', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
19                                                                                                                                                                                                                                                                        NaN
20         ['5 AC', '1 Chimney', '1 Modular Kitchen', 'No Bed', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
21                                                                                                                                                                                                                                                                         []
22           ['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '20 Light', '5 AC', '1 Modular Kitchen', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Geyser', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
23                                                                                                                                                                                                                                                                        NaN
24         ['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
25                                                                                                                                                                                                                                                                        NaN
26           ['6 Fan', '1 Exhaust Fan', '4 Geyser', '55 Light', '1 Chimney', '1 Modular Kitchen', '10 Wardrobe', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
27                                                                                                                                                                                                                                                                        NaN
28       ['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
29                                                                                                                                                                                                                                                                        NaN
30           ['7 Fan', '11 Light', '7 AC', '1 Modular Kitchen', '1 Chimney', '1 Curtains', 'No Bed', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
31        ['1 Modular Kitchen', '2 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
32                                                                                                                                                                                                                                                                        NaN
33       ['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
34                                                                                                                                                                                                                                                                        NaN
35                                                                                                                                                                                                                                                                        NaN
36        ['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
37            ['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Geyser', '10 Light', '1 Modular Kitchen', '1 Chimney', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
38               ['3 Bed', '5 Wardrobe', '6 Fan', '1 Sofa', '1 Exhaust Fan', '1 Dining Table', '3 Geyser', '2 TV', '1 Curtains', 'No AC', 'No Chimney', 'No Modular Kitchen', 'No Light', 'No Microwave', 'No Fridge', 'No Stove', 'No Washing Machine', 'No Water Purifier']
39       ['1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
40                                                                                                                                                                                                                                                                         []
41                                                                                                                                                                                                                                                                        NaN
42           ['2 Fan', '2 Geyser', '6 Light', '1 Chimney', '2 Wardrobe', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
43                                                                                                                                                                                                                                                                         []
44            ['8 Fan', '1 Exhaust Fan', '6 Geyser', '1 Stove', '10 Light', '1 Modular Kitchen', '1 Chimney', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
45          ['3 Fan', '2 Geyser', '7 Light', '3 AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
46        ['1 Exhaust Fan', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
47                  ['1 Water Purifier', '7 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geyser', '1 Stove', '10 Light', '5 AC', '1 Modular Kitchen', '1 Chimney', '3 Wardrobe', '1 Washing Machine', '1 Microwave', 'No Bed', 'No Curtains', 'No Dining Table', 'No Sofa', 'No TV']
48              ['1 Fan', '1 Exhaust Fan', '1 Geyser', '1 Light', '1 AC', '1 Modular Kitchen', '1 Chimney', '1 Curtains', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
49           ['1 Bed', '1 Wardrobe', '1 Fan', '1 Light', '1 AC', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
50                     ['1 Water Purifier', '2 Fan', '1 Fridge', '1 Exhaust Fan', '1 Geyser', '1 Stove', '5 Light', '1 Modular Kitchen', '1 Chimney', '1 Curtains', '2 Bed', '2 Wardrobe', '1 Sofa', '1 Washing Machine', '1 Microwave', 'No AC', 'No Dining Table', 'No TV']
51                                                                                                                                                                                                                                                                        NaN
52       ['1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
53           ['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Geyser', '6 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
54             ['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '1 Geyser', '1 Light', '1 Modular Kitchen', '1 Chimney', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
55         ['7 Fan', '7 Light', '3 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
56           ['1 Wardrobe', '1 Fan', '2 Light', '1 TV', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No Washing Machine', 'No Water Purifier']
57            ['1 Wardrobe', '1 Fan', '1 Geyser', '1 Light', '1 AC', '1 Chimney', 'No Bed', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
58                                                                                                                                                                                                                                                                        NaN
59       ['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
60                                                                                                                                                                                                                                                                         []
61             ['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Stove', '1 Microwave', '11 Light', '1 Modular Kitchen', '1 Chimney', 'No AC', 'No Bed', 'No Curtains', 'No Dining Table', 'No Geyser', 'No Fridge', 'No Sofa', 'No TV', 'No Washing Machine', 'No Water Purifier']
62                                                                                                                                                                                                                                                                         []
63                                                                                                                                                                                                                                                                         []
64                                                                                                                                                                                                                                                                         []
65                                                                                                                                                                                                                                                                         []
66       ['1 Light', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
67                                                                                                                                                                                                                                                                        NaN
68                                                                                                                                                                                                                                                                         []
69                                                                                                                                                                                                                                                                        NaN
70            ['6 Fan', '1 Exhaust Fan', '1 Chimney', '4 Curtains', '1 Modular Kitchen', '4 Wardrobe', 'No AC', 'No Bed', 'No Dining Table', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
71                                                                                                                                                                                                                                                                        NaN
72            ['1 Bed', '1 Fan', '1 Geyser', '1 Light', '1 AC', '1 TV', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']
73                                                                                                                                                                                                                                                                        NaN